### PR TITLE
English

### PR DESCRIPTION
**Pull request by Winael**

### CODE REVIEW

**Comment by adam-stokes** [comment]
Thanks! I'm looking into the best way to provide translation for our docs as well (we use gitbook locally)

**Comment by Winael** [comment]
@battlemidget markdown is very difficult to internationalize. I was unsuccessful to find a tool to generate pot files unfortunately. So I'm translated the pages in the old fashion way.

**Comment by adam-stokes** [comment]
Thank you for that, maybe I should look at another documentation tool that supports this?

**Comment by Winael** [comment]
@battlemidget Not necessary. As I read into pandoc documentation, it is possible to create filters to extract string, and do some suff. So basically, it is possible to create a tools. @dplanella try to create one but failed on quote characters, I don't know if it is fixed.

As a non-dev people, it's hard to help on this part. So for now, I just comment english part and add translation into md files.

**Comment by adam-stokes** [comment]
Ok thanks

**Pull request merged**
